#!/bin/bash
while getopts ":u:p:t:n:a:d:c:hA:" FLAG; do
	case $FLAG in
		u)
			REPO_URL=$OPTARG
			;;
		t)
			REPO_TYPE=$OPTARG
			;;
		p)
			PROJECT=$OPTARG
			;;
		a)
			ARCH=$OPTARG
			;;
		n)
			REPO_NAME=$OPTARG
			;;
		d)
			UBUNTU_DISTRO=$OPTARG
			;;
		c)
			UBUNTU_REPO_COMPONENT=$OPTARG
			;;
		A)
			OBS_SERV_URL=$OPTARG
			;;
		\?)
			echo "Invalid option: -$OPTARG. Use -h for help" >&2
			exit 1
			;;
		:)
			echo "Option -$OPTARG requires an argument." >&2
			exit 1
			;;
		h)
			echo -e "Usage: $(basename $0) [-A <obs_url>] -u <source_repo_url> -p <obs_project> -n <repository_name> [-t <repo_type>=RPM] [-a <arch>=x86_64] \
[-d <ubuntu_distro>=precise] [-c <ubuntu_repo_component>=main]\n\n \
-u <source_repo_url> 		- URL of repository project connected to. Needed for downloading repo index files.\n \
-p <obs_project>     		- name of OBS project for linking (activating).\n \
-n <repository_name> 		- desired name of OBS project's repository.\n \
[-A <obs_url>]			- target OBS server API URL. Default value: OBS_DEST env variable.\n \
[-t <repo_type>]     		- deb or rpm repository. Default value: RPM.\n \
[-a <arch>]          		- repository architecture. Default value: x86_64.\n \
[-d <ubuntu_distro>=precise]	- UBUNTU ONLY: Ubuntu distribution (code name). Default value: precise.\n \
[-c <ubuntu_repo_component>=main]-UBUNTU ONLY: Ubuntu repo component, e.g. main, universe, multiverse etc. Default value: main."
				
			exit
			;;
	esac
done
shift $((OPTIND-1))

if [[ -z "$REPO_URL" || -z "$PROJECT" || -z "$REPO_NAME" ]]; then
	echo "Invalid usage. <repo_url>, <obs-project> and <repository_name> arguments are mandatory. Use -h fo help."
	exit 1
fi
[[ -z "$OBS_SERV_URL" ]] && OBS_SERV_URL=$OBS_DEST
[[ -z "$REPO_TYPE" ]] && REPO_TYPE="RPM"
[[ -z "$ARCH" ]] && ARCH="x86_64"
[[ -z "$UBUNTU_DISTRO" ]] && UBUNTU_DISTRO="precise"
[[ -z "$UBUNTU_REPO_COMPONENT" ]] && UBUNTU_REPO_COMPONENT="main"
case "$REPO_TYPE" in
	"RPM"|"rpm")
		INDEX_TYPE="primary.xml.gz"
		# determine exact path to primary.xml.gz file in repodata
		INDEX_URL="${REPO_URL%/}/repodata/$(curl ${INDEX_URL%/}/repodata/ | grep -o '[0-9a-hA-H-]*primary\.xml\.gz' | uniq)"
		UNZIPPER="gunzip"
		;;
	"DEB"|"deb")
		INDEX_TYPE="Packages.gz"
		DIST="precise"

		INDEX_URL="${REPO_URL%/}/dist/$UBUNTU_DISTRO/$UBUNTU_REPO_COMPONENT/binary-$(echo $ARCH | sed 's|^x86_64$|amd64|;s|^x86$|i386|')/$INDEX_TYPE"
		UNZIPPER="gunzip"
		;;
	*)
		echo "Invalid package_type. Should be either RPM or DEB"
		exit 1
		;;
esac
# create target/external project on destination OBS
if ! osc -A $OBS_DEST meta prj -F - $PROJECT <<EOF
<project name="internal:ubuntu-osci-builddeps-5.1">
  <title/>
  <description/>
  <person userid="Admin" role="bugowner"/>
  <person userid="Admin" role="maintainer"/>
  <download baseurl="$INDEX_URL" metafile="${INDEX_TYPE%.*}" mtype="$(echo $REPO_TYPE | tr '[:upper:]' '[:lower:]')md" arch="$ARCH"/>
  <repository name="$UBUNTU_DISTRO-$UBUNTU_REPO_COMPONENT">
    <arch>$ARCH</arch>
  </repository>
</project>
EOF
then

	echo "Project wasn't created. Exitting..."
	exit 1
fi
if [[ ! -d /srv/obs/build/$PROJECT/$REPO_NAME/$ARCH/:full ]]; then
	if ! mkdir -p /srv/obs/build/$PROJECT/$REPO_NAME/$ARCH/:full; then echo ":full directory for project $PROJECT wasn't created. Exitting..."; exit 2; fi
else
	rm -rf /srv/obs/build/$PROJECT/$REPO_NAME/$ARCH/:full/*
fi
[[ -e /srv/obs/build/$PROJECT/$REPO_NAME/$ARCH/:full.solv ]] && rm -f /srv/obs/build/$PROJECT/$REPO_NAME/$ARCH/:full.solv
wget -O "/srv/obs/build/$PROJECT/$REPO_NAME/$ARCH/:full/$INDEX_TYPE" $INDEX_URL
$UNZIPPER "/srv/obs/build/$PROJECT/$REPO_NAME/$ARCH/:full/$INDEX_TYPE"
chown -R obsrun:obsrun "/srv/obs/build/$PROJECT"
obs_admin --rescan-repository $PROJECT $REPO_NAME $ARCH
