#!/bin/bash -x
OBS_DST=$OBS_DEST
OBS_SRC=$OBS_SOURCE
PROJ_LIST=$PROJECT_LIST
while getopts ":s:d:p:h" FLAG; do
	case $FLAG in
		s)
			OBS_SRC=$OPTARG
			;;
		d)
			OBS_DST=$OPTARG
			;;
		p)
			PROJ_LIST="$OPTARG"
			;;
		\?)
			echo "Invalid option: -$OPTARG. Use -h for help" >&2
			exit 1
			;;
		:)
			echo "Option -$OPTARG requires an argument." >&2
			exit 1
			;;
		h)
			echo -e "This script 'de-aggregates' given projects, e.g. recursively finds 'parent' project/package pair for all aggregated OBS packages in specified projects and replaces _aggregated files on specs and source tarballs from this parent project.\n\nUsage: $(basename $0) [-s <source_obs_url>] [-d <dest_obs_url>] [-p <obs_project_list>]\n\n \
[-s <source_obs_url]		- Optional. Source OBS server API URL. Default value: env variable OBS_SOURCE\n \
[-d <dest_obs_url]		- Optional. Destination OBS server API URL. Default value: env variable OBS_DEST\n \
[-p <obs_project_list>]     	- Optional. List of projects to de-aggregate. Default value: env variable PROJECT_LIST." 
			exit
			;;
	esac
done
shift $((OPTIND-1))
find_source_project()
{
	local proj=$1
	#local package=$2
	local temp_dir="/tmp/checkout"
	echo "Trying to determine root project for package $package in project $proj"
	if ! mkdir -p $temp_dir; then  echo "Cannot create temporary dir. Exitting"; return 1; fi
	# checkout package	
	osc -A $OBS_SRC checkout $proj $package -o $temp_dir
	if [[ ! -e "$temp_dir/_aggregate" ]]
	then
		echo "ERROR: Package $package in project $proj doesn't contain _aggregate file"
		rm -rf $temp_dir
		return 1
	fi
	# in _aggregate file find project aggregated from
	src_prj="$(grep "^.*aggregate.*project" $temp_dir/_aggregate | sed 's|^.*aggregate.*project="||g;s|">.*||g')"
	# in _aggregate file find package name aggregated to
	package="$(grep "^.*<package>.*</package>" $temp_dir/_aggregate | sed 's|^.*<package>||g;s|<.*||g')"
	rm -rf $temp_dir
	if ! $(osc -A $OBS_SRC ls $src_prj &>/dev/null); then
		echo "ERROR: Source project $src_prj for aggregated package $pkg doesn't exist!"
		return 1
	fi
	if [[ "$(osc -A $OBS_SRC ls $src_prj $package)" == "_aggregate" ]]; then
		find_source_project $src_prj
	fi
	return 0
}
if [[ -z "$OBS_DST" || -z "$OBS_SRC" || -z "$PROJ_LIST" ]]; then
	echo "Invalid usage. Specify URL to OBS servers and projects you want to de-aggregate. Use -h fo help."
	exit 1
fi
for PROJECT in $PROJ_LIST; do
for pkg in $(osc -A $OBS_DST ls $PROJECT); do
	if [[ "$(osc -A $OBS_DST ls $PROJECT $pkg)" == "_aggregate" ]]; then
		package=$pkg
		find_source_project $PROJECT
		if [[ "$?" == 0 && -n "$src_prj" ]]; then
			# delete old package
			osc -A $OBS_DST rdelete $PROJECT $pkg -m "$pkg package aggregation is replaced on usual package"
			# copy new one from real source project on source OBS server
			osc -A $OBS_SRC copypac -t $OBS_DST $src_prj $package $PROJECT $pkg
			# copy new package metadata
			#osc -A $OBS_SRC meta pkg $src_prj $pkg > $pkg.newpkg
			# set up pkg meta
			osc -A $OBS_DST meta pkg -F - $PROJECT $pkg <<METAEOF
<package name="$pkg" project="$PROJECT">
  <title></title>
  <description></description>
</package>
METAEOF
			# clean temporary file
			#rm -f $pkg.newpkg
		else
			echo "ERROR: Root project for aggregated package $pkg wasn't determined"
			continue
		fi
	fi
done
done
