#!/bin/bash
REPO_URL=$1
DEST_PROJECT=$2
REPO_NAME=$3
ARCH=$4
TEMP_DIR=$5
if [[ -z "$REPO_URL" || -z "$DEST_PROJECT" || -z "$REPO_NAME" ]]; then
	echo -e "Invalid usage\nUsage: $(basename $0) <source_repo_url> <target_project_name> <repo_name> [<arch>=x86_64] [<destination_dir>=/data/imports]\n"
	exit 1
fi
if [[ -z "$TEMP_DIR" || -z "$ARCH" ]]; then
	TEMP_DIR="/data/imports"
	ARCH="x86_64"
	echo -e "You didn't specify full path to destination directory and/or repo arch. $TEMP_DIR will be used as default repo location. $ARCH arch is assumed\n"
fi
if [[ ! -d "$TEMP_DIR" ]]; then
	if ! mkdir -p "$TEMP_DIR"; then echo "Destination directory wasn't created. Exitting..."; exit 2; fi
else
	rm -rf $TEMP_DIR/*
fi
WGET_CUT_DIRS="$(echo $REPO_URL |sed  "s,[a-zA-Z0-9]*://,,;s,\/, ,g" | wc -w)"
if [[ ! -d "/srv/obs/build/$DEST_PROJECT/$REPO_NAME/$ARCH/:full" ]]; then
	if ! mkdir -p /srv/obs/build/$DEST_PROJECT/$REPO_NAME/$ARCH/:full; then echo ":full directory for project $DEST_PROJECT wasn't created. Exitting..."; exit 2; fi
else
	rm -rf /srv/obs/build/$DEST_PROJECT/$REPO_NAME/$ARCH/:full/*
fi
rcobsscheduler shutdown
wget --directory-prefix="$TEMP_DIR" --reject index.html* --mirror --no-parent --no-host-directories --cut-dirs="$WGET_CUT_DIRS" $REPO_URL
# Rename RPMs as <name>.rpm (without any versions and releases) and move to :full directory of target project
for i in `find "$TEMP_DIR" -name \*.rpm`; 
do
	 j=`basename $i`
	 k=`echo $j |sed -rn 's/(.*)-.*-.*.rpm/\1.rpm/p'`
	 mv $i /srv/obs/build/$DEST_PROJECT/$REPO_NAME/$ARCH/:full/$k 
done
mv `find "$TEMP_DIR" -name "*primary.xml.gz"` $TEMP_DIR/primary.xml.gz
gunzip $TEMP_DIR/primary.xml.gz
mv $TEMP_DIR/primary.xml /srv/obs/build/$DEST_PROJECT/$REPO_NAME/$ARCH/:full/
chown -R obsrun:obsrun /srv/obs/build/$DEST_PROJECT
rm -rf $TEMP_DIR
obs_admin --rescan-repository $DEST_PROJECT $REPO_NAME $ARCH
rcobsscheduler start
